openapi: 3.2.0
info:
  title: ElevenLabs API Documentation Audio Native API
  description: This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your API key. You can find your API key in the dashboard at https://elevenlabs.io/app/settings/api-keys.
  version: '1.0'
tags:
- name: audio-native
  description: Embed AI-narrated audio players into your website using Audio Native.
paths:
  /v1/audio-native:
    post:
      tags:
      - audio-native
      summary: Creates Audio Native Enabled Project
      description: Creates Audio Native enabled project, optionally starts conversion and returns project ID and embeddable HTML snippet.
      operationId: create_audio_native_project
      parameters:
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_Creates_Audio_Native_enabled_project__v1_audio_native_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AudioNativeCreateProjectResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: audio_native
      x-fern-sdk-method-name: create
  /v1/audio-native/{project_id}/settings:
    get:
      tags:
      - audio-native
      summary: Get Audio Native Project Settings
      description: Get player settings for the specific project.
      operationId: get_audio_native_project_settings_endpoint
      parameters:
      - name: project_id
        in: path
        required: true
        schema:
          type: string
          description: The ID of the Studio project.
          examples:
          - 21m00Tcm4TlvDq8ikWAM
          title: Project Id
        description: The ID of the Studio project.
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAudioNativeProjectSettingsResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: audio_native
      x-fern-sdk-method-name: get_settings
  /v1/audio-native/{project_id}/content:
    post:
      tags:
      - audio-native
      summary: Update Audio-Native Project Content
      description: Updates content for the specific AudioNative Project.
      operationId: audio_native_project_update_content_endpoint
      parameters:
      - name: project_id
        in: path
        required: true
        schema:
          type: string
          description: The ID of the Studio project.
          examples:
          - 21m00Tcm4TlvDq8ikWAM
          title: Project Id
        description: The ID of the Studio project.
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_Update_audio_native_Project_content_v1_audio_native__project_id__content_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AudioNativeEditContentResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: audio_native
      x-fern-sdk-method-name: update
  /v1/audio-native/content:
    post:
      tags:
      - audio-native
      summary: Update Audio-Native Content From Url
      description: Finds an AudioNative project matching the provided URL, extracts content from the URL, updates the project content, and queues it for conversion and auto-publishing.
      operationId: audio_native_update_content_from_url
      parameters:
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_Update_audio_native_content_from_URL_v1_audio_native_content_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AudioNativeEditContentResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: audio_native
      x-fern-sdk-method-name: update_content_from_url
components:
  schemas:
    Body_Creates_Audio_Native_enabled_project__v1_audio_native_post:
      properties:
        name:
          type: string
          title: Name
          description: Project name.
        image:
          anyOf:
          - type: string
          - type: 'null'
          title: Image
          description: (Deprecated) Image URL used in the player. If not provided, default image set in the Player settings is used.
          deprecated: true
        author:
          anyOf:
          - type: string
          - type: 'null'
          title: Author
          description: Author used in the player and inserted at the start of the uploaded article. If not provided, the default author set in the Player settings is used.
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
          description: Title used in the player and inserted at the top of the uploaded article. If not provided, the default title set in the Player settings is used.
        small:
          type: boolean
          title: Small
          description: (Deprecated) Whether to use small player or not. If not provided, default value set in the Player settings is used.
          default: false
          deprecated: true
        text_color:
          anyOf:
          - type: string
          - type: 'null'
          title: Text Color
          description: Text color used in the player. If not provided, default text color set in the Player settings is used.
        background_color:
          anyOf:
          - type: string
          - type: 'null'
          title: Background Color
          description: Background color used in the player. If not provided, default background color set in the Player settings is used.
        sessionization:
          type: integer
          title: Sessionization
          description: (Deprecated) Specifies for how many minutes to persist the session across page reloads. If not provided, default sessionization set in the Player settings is used.
          default: 0
          deprecated: true
        voice_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Voice Id
          description: Voice ID used to voice the content. If not provided, default voice ID set in the Player settings is used.
        model_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Model Id
          description: TTS Model ID used in the player. If not provided, default model ID set in the Player settings is used.
        file:
          type: string
          title: File
          description: Either txt or HTML input file containing the article content. HTML should be formatted as follows '&lt;html&gt;&lt;body&gt;&lt;div&gt;&lt;p&gt;Your content&lt;/p&gt;&lt;h3&gt;More of your content&lt;/h3&gt;&lt;p&gt;Some more of your content&lt;/p&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;'
          format: binary
        auto_convert:
          type: boolean
          title: Auto Convert
          description: Whether to auto convert the project to audio or not.
          default: false
        apply_text_normalization:
          anyOf:
          - type: string
            enum:
            - auto
            - 'on'
            - 'off'
            - apply_english
          - type: 'null'
          title: Apply Text Normalization
          description: "\n    This parameter controls text normalization with four modes: 'auto', 'on', 'apply_english' and 'off'.\n    When set to 'auto', the system will automatically decide whether to apply text normalization\n    (e.g., spelling out numbers). With 'on', text normalization will always be applied, while\n    with 'off', it will be skipped. 'apply_english' is the same as 'on' but will assume that text is in English.\n    "
        pronunciation_dictionary_locators:
          items:
            type: string
          type: array
          title: Pronunciation Dictionary Locators
          description: A list of pronunciation dictionary locators (pronunciation_dictionary_id, version_id) encoded as a list of JSON strings for pronunciation dictionaries to be applied to the text. A list of json encoded strings is required as adding projects may occur through formData as opposed to jsonBody. To specify multiple dictionaries use multiple --form lines in your curl, such as --form 'pronunciation_dictionary_locators="{\"pronunciation_dictionary_id\":\"Vmd4Zor6fplcA7WrINey\",\"version_id\":\"hRPaxjlTdR7wFMhV4w0b\"}"' --form 'pronunciation_dictionary_locators="{\"pronunciation_dictionary_id\":\"JzWtcGQMJ6bnlWwyMo7e\",\"version_id\":\"lbmwxiLu4q6txYxgdZqn\"}"'.
          examples:
          - - '{"pronunciation_dictionary_id": "21m00Tcm4TlvDq8ikWAM", "version_id": "BdF0s0aZ3oFoKnDYdTox"}'
      type: object
      required:
      - name
      title: Body_Creates_Audio_Native_enabled_project__v1_audio_native_post
    Body_Update_audio_native_Project_content_v1_audio_native__project_id__content_post:
      properties:
        file:
          type: string
          title: File
          description: Either txt or HTML input file containing the article content. HTML should be formatted as follows '&lt;html&gt;&lt;body&gt;&lt;div&gt;&lt;p&gt;Your content&lt;/p&gt;&lt;h5&gt;More of your content&lt;/h5&gt;&lt;p&gt;Some more of your content&lt;/p&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;'
          format: binary
        auto_convert:
          type: boolean
          title: Auto Convert
          description: Whether to auto convert the project to audio or not.
          default: false
        auto_publish:
          type: boolean
          title: Auto Publish
          description: Whether to auto publish the new project snapshot after it's converted.
          default: false
      type: object
      title: Body_Update_audio_native_Project_content_v1_audio_native__project_id__content_post
    GetAudioNativeProjectSettingsResponseModel:
      properties:
        enabled:
          type: boolean
          title: Enabled
          description: Whether the project is enabled.
        snapshot_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Snapshot Id
          description: The ID of the latest snapshot of the project.
        settings:
          anyOf:
          - $ref: '#/components/schemas/AudioNativeProjectSettingsResponseModel'
          - type: 'null'
          description: The settings of the project.
      type: object
      required:
      - enabled
      title: GetAudioNativeProjectSettingsResponseModel
      example:
        enabled: true
        settings:
          audio_path: audio/my_project.mp3
          audio_url: https://example.com/audio/my_project.mp3
          author: John Doe
          background_color: '#FFFFFF'
          image: https://example.com/image.jpg
          sessionization: 1
          small: false
          status: ready
          text_color: '#000000'
          title: My Project
        snapshot_id: JBFqnCBsd6RMkjVDRZzb
    AudioNativeProjectSettingsResponseModel:
      properties:
        title:
          type: string
          title: Title
          description: The title of the project.
        image:
          type: string
          title: Image
          description: The image of the project.
        author:
          type: string
          title: Author
          description: The author of the project.
        small:
          type: boolean
          title: Small
          description: Whether the project is small.
        text_color:
          type: string
          title: Text Color
          description: The text color of the project.
        background_color:
          type: string
          title: Background Color
          description: The background color of the project.
        sessionization:
          type: integer
          title: Sessionization
          description: The sessionization of the project. Specifies for how many minutes to persist the session across page reloads.
        audio_path:
          anyOf:
          - type: string
          - type: 'null'
          title: Audio Path
          description: The path of the audio file.
        audio_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Audio Url
          description: The URL of the audio file.
        status:
          type: string
          enum:
          - processing
          - ready
          title: Status
          description: Current state of the project
          default: ready
      type: object
      required:
      - title
      - image
      - author
      - small
      - text_color
      - background_color
      - sessionization
      title: AudioNativeProjectSettingsResponseModel
      example:
        audio_path: audio/my_project.mp3
        audio_url: https://example.com/audio/my_project.mp3
        author: John Doe
        background_color: '#FFFFFF'
        image: https://example.com/image.jpg
        sessionization: 1
        small: false
        status: ready
        text_color: '#000000'
        title: My Project
    AudioNativeCreateProjectResponseModel:
      properties:
        project_id:
          type: string
          title: Project Id
          description: The ID of the created Audio Native project.
        converting:
          type: boolean
          title: Converting
          description: Whether the project is currently being converted.
        html_snippet:
          type: string
          title: Html Snippet
          description: The HTML snippet to embed the Audio Native player.
      type: object
      required:
      - project_id
      - converting
      - html_snippet
      title: AudioNativeCreateProjectResponseModel
      example:
        converting: false
        html_snippet: <div id='audio-native-player'></div>
        project_id: JBFqnCBsd6RMkjVDRZzb
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Body_Update_audio_native_content_from_URL_v1_audio_native_content_post:
      properties:
        url:
          type: string
          title: Url
          description: URL of the page to extract content from.
          examples:
          - https://elevenlabs.io/blog/the_first_ai_that_can_laugh/
        author:
          anyOf:
          - type: string
          - type: 'null'
          title: Author
          description: Author used in the player and inserted at the start of the uploaded article. If not provided, the default author set in the Player settings is used.
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
          description: Title used in the player and inserted at the top of the uploaded article. If not provided, the default title set in the Player settings is used.
      type: object
      required:
      - url
      title: Body_Update_audio_native_content_from_URL_v1_audio_native_content_post
    AudioNativeEditContentResponseModel:
      properties:
        project_id:
          type: string
          title: Project Id
          description: The ID of the project.
        converting:
          type: boolean
          title: Converting
          description: Whether the project is currently being converted.
        publishing:
          type: boolean
          title: Publishing
          description: Whether the project is currently being published.
        html_snippet:
          type: string
          title: Html Snippet
          description: The HTML snippet to embed the Audio Native player.
      type: object
      required:
      - project_id
      - converting
      - publishing
      - html_snippet
      title: AudioNativeEditContentResponseModel
      example:
        converting: false
        html_snippet: <div id='audio-native-player'></div>
        project_id: JBFqnCBsd6RMkjVDRZzb
        publishing: false
