openapi: 3.2.0
info:
  title: ElevenLabs API Documentation Pronunciation Dictionary API
  description: This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your API key. You can find your API key in the dashboard at https://elevenlabs.io/app/settings/api-keys.
  version: '1.0'
tags:
- name: Pronunciation Dictionary
  description: Manage pronunciation dictionaries that override how specific words are pronounced.
paths:
  /v1/pronunciation-dictionaries/add-from-file:
    post:
      tags:
      - Pronunciation Dictionary
      summary: Add A Pronunciation Dictionary
      description: Creates a new pronunciation dictionary from a lexicon .PLS file
      operationId: add_from_file
      parameters:
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_Add_a_pronunciation_dictionary_v1_pronunciation_dictionaries_add_from_file_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddPronunciationDictionaryResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: pronunciation_dictionaries
      x-fern-sdk-method-name: create_from_file
  /v1/pronunciation-dictionaries/add-from-rules:
    post:
      tags:
      - Pronunciation Dictionary
      summary: Add A Pronunciation Dictionary
      description: Creates a new pronunciation dictionary from provided rules.
      operationId: add_from_rules
      parameters:
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_Add_a_pronunciation_dictionary_v1_pronunciation_dictionaries_add_from_rules_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddPronunciationDictionaryResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: pronunciation_dictionaries
      x-fern-sdk-method-name: create_from_rules
  /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}:
    patch:
      tags:
      - Pronunciation Dictionary
      summary: Update Pronunciation Dictionary
      description: Partially update the pronunciation dictionary without changing the version
      operationId: patch_pronunciation_dictionary
      parameters:
      - name: pronunciation_dictionary_id
        in: path
        required: true
        schema:
          type: string
          description: The id of the pronunciation dictionary
          examples:
          - 21m00Tcm4TlvDq8ikWAM
          title: Pronunciation Dictionary Id
        description: The id of the pronunciation dictionary
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_Update_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__patch'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPronunciationDictionaryMetadataResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: pronunciation_dictionaries
      x-fern-sdk-method-name: update
    get:
      tags:
      - Pronunciation Dictionary
      summary: Get Metadata For A Pronunciation Dictionary
      description: Get metadata for a pronunciation dictionary
      operationId: get_pronunciation_dictionary_metadata
      parameters:
      - name: pronunciation_dictionary_id
        in: path
        required: true
        schema:
          type: string
          description: The id of the pronunciation dictionary
          examples:
          - 21m00Tcm4TlvDq8ikWAM
          title: Pronunciation Dictionary Id
        description: The id of the pronunciation dictionary
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPronunciationDictionaryWithRulesResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: pronunciation_dictionaries
      x-fern-sdk-method-name: get
  /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}/set-rules:
    post:
      tags:
      - Pronunciation Dictionary
      summary: Set Rules On The Pronunciation Dictionary
      description: Replaces all existing rules on the pronunciation dictionary with the provided ones.
      operationId: set_rules
      parameters:
      - name: pronunciation_dictionary_id
        in: path
        required: true
        schema:
          type: string
          description: The id of the pronunciation dictionary
          examples:
          - 21m00Tcm4TlvDq8ikWAM
          title: Pronunciation Dictionary Id
        description: The id of the pronunciation dictionary
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_Set_rules_on_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__set_rules_post'
      responses:
        '200':
          description: Successfully set rules on the pronunciation dictionary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PronunciationDictionaryRulesResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name:
      - pronunciation_dictionaries
      - rules
      x-fern-sdk-method-name: set
  /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}/add-rules:
    post:
      tags:
      - Pronunciation Dictionary
      summary: Add Rules To The Pronunciation Dictionary
      description: Add rules to the pronunciation dictionary. If a rule with the same string_to_replace already exists, it will be replaced.
      operationId: add_rules
      parameters:
      - name: pronunciation_dictionary_id
        in: path
        required: true
        schema:
          type: string
          description: The id of the pronunciation dictionary
          examples:
          - 21m00Tcm4TlvDq8ikWAM
          title: Pronunciation Dictionary Id
        description: The id of the pronunciation dictionary
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_Add_rules_to_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__add_rules_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PronunciationDictionaryRulesResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name:
      - pronunciation_dictionaries
      - rules
      x-fern-sdk-method-name: add
  /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}/remove-rules:
    post:
      tags:
      - Pronunciation Dictionary
      summary: Remove Rules From The Pronunciation Dictionary
      description: Remove rules from the pronunciation dictionary
      operationId: remove_rules
      parameters:
      - name: pronunciation_dictionary_id
        in: path
        required: true
        schema:
          type: string
          description: The id of the pronunciation dictionary
          examples:
          - 21m00Tcm4TlvDq8ikWAM
          title: Pronunciation Dictionary Id
        description: The id of the pronunciation dictionary
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_Remove_rules_from_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__remove_rules_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PronunciationDictionaryRulesResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name:
      - pronunciation_dictionaries
      - rules
      x-fern-sdk-method-name: remove
  /v1/pronunciation-dictionaries/{dictionary_id}/{version_id}/download:
    get:
      tags:
      - Pronunciation Dictionary
      summary: Get A Pls File With A Pronunciation Dictionary Version Rules
      description: Get a PLS file with a pronunciation dictionary version rules
      operationId: get_pronunciation_dictionary_version_pls
      parameters:
      - name: dictionary_id
        in: path
        required: true
        schema:
          type: string
          description: The id of the pronunciation dictionary
          examples:
          - 21m00Tcm4TlvDq8ikWAM
          title: Dictionary Id
        description: The id of the pronunciation dictionary
      - name: version_id
        in: path
        required: true
        schema:
          type: string
          description: The id of the pronunciation dictionary version
          examples:
          - BdF0s0aZ3oFoKnDYdTox
          title: Version Id
        description: The id of the pronunciation dictionary version
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      responses:
        '200':
          description: The PLS file containing pronunciation dictionary rules
          content:
            text/plain:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              description: Attachment filename
              schema:
                type: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: pronunciation_dictionaries
      x-fern-sdk-method-name: download
  /v1/pronunciation-dictionaries:
    get:
      tags:
      - Pronunciation Dictionary
      summary: Get Pronunciation Dictionaries
      description: Get a list of the pronunciation dictionaries you have access to and their metadata
      operationId: get_pronunciation_dictionaries_metadata
      parameters:
      - name: cursor
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Used for fetching next page. Cursor is returned in the response.
          title: Cursor
        description: Used for fetching next page. Cursor is returned in the response.
      - name: page_size
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
          description: How many pronunciation dictionaries to return at maximum. Can not exceed 100, defaults to 30.
          default: 30
          title: Page Size
        description: How many pronunciation dictionaries to return at maximum. Can not exceed 100, defaults to 30.
      - name: sort
        in: query
        required: false
        schema:
          anyOf:
          - enum:
            - creation_time_unix
            - name
            type: string
          - type: 'null'
          description: Which field to sort by, one of 'created_at_unix' or 'name'.
          examples:
          - creation_time_unix
          default: creation_time_unix
          title: Sort
        description: Which field to sort by, one of 'created_at_unix' or 'name'.
      - name: sort_direction
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Which direction to sort the voices in. 'ascending' or 'descending'.
          examples:
          - descending
          default: DESCENDING
          title: Sort Direction
        description: Which direction to sort the voices in. 'ascending' or 'descending'.
      - name: include_archived
        in: query
        required: false
        schema:
          type: boolean
          description: Whether to include archived pronunciation dictionaries in the response.
          examples:
          - false
          default: true
          title: Include Archived
        description: Whether to include archived pronunciation dictionaries in the response.
      - name: xi-api-key
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
          title: Xi-Api-Key
        description: Your API key. This is required by most endpoints to access our API programmatically. You can view your xi-api-key using the 'Profile' tab on the website.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPronunciationDictionariesMetadataResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-fern-sdk-group-name: pronunciation_dictionaries
      x-fern-sdk-method-name: list
components:
  schemas:
    AddPronunciationDictionaryResponseModel:
      properties:
        id:
          type: string
          title: Id
          description: The ID of the created pronunciation dictionary.
        name:
          type: string
          title: Name
          description: The name of the created pronunciation dictionary.
        created_by:
          type: string
          title: Created By
          description: The user ID of the creator of the pronunciation dictionary.
        creation_time_unix:
          type: integer
          title: Creation Time Unix
          description: The creation time of the pronunciation dictionary in Unix timestamp.
        version_id:
          type: string
          title: Version Id
          description: The ID of the created pronunciation dictionary version.
        version_rules_num:
          type: integer
          title: Version Rules Num
          description: The number of rules in the version of the pronunciation dictionary.
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
          description: The description of the pronunciation dictionary.
        permission_on_resource:
          anyOf:
          - type: string
            enum:
            - admin
            - editor
            - commenter
            - viewer
          - type: 'null'
          title: Permission On Resource
          description: The permission on the resource of the pronunciation dictionary.
      type: object
      required:
      - id
      - name
      - created_by
      - creation_time_unix
      - version_id
      - version_rules_num
      - permission_on_resource
      title: AddPronunciationDictionaryResponseModel
      example:
        created_by: ar6633Es2kUjFXBdR1iVc9ztsXl1
        creation_time_unix: 1714156800
        description: This is a test dictionary
        id: 5xM3yVvZQKV0EfqQpLrJ
        name: My Dictionary
        permission_on_resource: admin
        version_id: 5xM3yVvZQKV0EfqQpLrJ
        version_rules_num: 5
    GetPronunciationDictionaryWithRulesResponseModel:
      properties:
        id:
          type: string
          title: Id
          description: The ID of the pronunciation dictionary.
        latest_version_id:
          type: string
          title: Latest Version Id
          description: The ID of the latest version of the pronunciation dictionary.
        latest_version_rules_num:
          type: integer
          title: Latest Version Rules Num
          description: The number of rules in the latest version of the pronunciation dictionary.
        name:
          type: string
          title: Name
          description: The name of the pronunciation dictionary.
        permission_on_resource:
          anyOf:
          - type: string
            enum:
            - admin
            - editor
            - commenter
            - viewer
          - type: 'null'
          title: Permission On Resource
          description: The permission on the resource of the pronunciation dictionary.
        created_by:
          type: string
          title: Created By
          description: The user ID of the creator of the pronunciation dictionary.
        creation_time_unix:
          type: integer
          title: Creation Time Unix
          description: The creation time of the pronunciation dictionary in Unix timestamp.
        archived_time_unix:
          anyOf:
          - type: integer
          - type: 'null'
          title: Archived Time Unix
          description: The archive time of the pronunciation dictionary in Unix timestamp.
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
          description: The description of the pronunciation dictionary.
        rules:
          items:
            anyOf:
            - $ref: '#/components/schemas/PronunciationDictionaryAliasRuleResponseModel'
            - $ref: '#/components/schemas/PronunciationDictionaryPhonemeRuleResponseModel'
          type: array
          title: Rules
          description: The rules in the latest version of the pronunciation dictionary.
      type: object
      required:
      - id
      - latest_version_id
      - latest_version_rules_num
      - name
      - permission_on_resource
      - created_by
      - creation_time_unix
      - rules
      title: GetPronunciationDictionaryWithRulesResponseModel
      example:
        created_by: ar6633Es2kUjFXBdR1iVc9ztsXl1
        creation_time_unix: 1714156800
        description: This is a test dictionary
        id: 5xM3yVvZQKV0EfqQpLrJ
        latest_version_id: 5xM3yVvZQKV0EfqQpLr2
        latest_version_rules_num: 2
        name: My Dictionary
        permission_on_resource: admin
        rules:
        - alias: tie-land
          string_to_replace: Thailand
          type: alias
        - alphabet: ipa
          phoneme: /təˈmeɪtoʊ/
          string_to_replace: Tomato
          type: phoneme
    GetPronunciationDictionariesMetadataResponseModel:
      properties:
        pronunciation_dictionaries:
          items:
            $ref: '#/components/schemas/GetPronunciationDictionaryMetadataResponseModel'
          type: array
          title: Pronunciation Dictionaries
          description: A list of pronunciation dictionaries and their metadata.
        next_cursor:
          anyOf:
          - type: string
          - type: 'null'
          title: Next Cursor
          description: The next cursor to use for pagination.
        has_more:
          type: boolean
          title: Has More
          description: Whether there are more pronunciation dictionaries to fetch.
      type: object
      required:
      - pronunciation_dictionaries
      - has_more
      title: GetPronunciationDictionariesMetadataResponseModel
      example:
        has_more: false
        next_cursor: 5xM3yVvZQKV0EfqQpLr2
        pronunciation_dictionaries:
        - created_by: ar6633Es2kUjFXBdR1iVc9ztsXl1
          creation_time_unix: 1714156800
          description: This is a test dictionary
          id: 5xM3yVvZQKV0EfqQpLrJ
          latest_version_id: 5xM3yVvZQKV0EfqQpLr2
          latest_version_rules_num: 2
          name: My Dictionary
          permission_on_resource: admin
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    PronunciationDictionaryRulesResponseModel:
      properties:
        id:
          type: string
          title: Id
          description: The ID of the pronunciation dictionary.
        version_id:
          type: string
          title: Version Id
          description: The version ID of the pronunciation dictionary.
        version_rules_num:
          type: integer
          title: Version Rules Num
          description: The number of rules in the version of the pronunciation dictionary.
      type: object
      required:
      - id
      - version_id
      - version_rules_num
      title: PronunciationDictionaryRulesResponseModel
      example:
        id: 5xM3yVvZQKV0EfqQpLrJ
        version_id: 5xM3yVvZQKV0EfqQpLr2
        version_rules_num: 5
    Body_Add_rules_to_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__add_rules_post:
      properties:
        rules:
          items:
            anyOf:
            - $ref: '#/components/schemas/PronunciationDictionaryAliasRuleRequestModel'
            - $ref: '#/components/schemas/PronunciationDictionaryPhonemeRuleRequestModel'
          type: array
          title: Rules
          description: "List of pronunciation rules. Rule can be either:\n    an alias rule: {'string_to_replace': 'a', 'type': 'alias', 'alias': 'b', }\n    or a phoneme rule: {'string_to_replace': 'a', 'type': 'phoneme', 'phoneme': 'b', 'alphabet': 'ipa' }"
          examples:
          - "\n    [\n        {'string_to_replace': 'a', 'type': 'alias', 'alias': 'b' },\n        {'string_to_replace': 'c', 'type': 'phoneme', 'phoneme': 'd', 'alphabet': 'ipa' }\n    ]"
      type: object
      required:
      - rules
      title: Body_Add_rules_to_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__add_rules_post
    Body_Set_rules_on_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__set_rules_post:
      properties:
        rules:
          items:
            anyOf:
            - $ref: '#/components/schemas/PronunciationDictionaryAliasRuleRequestModel'
            - $ref: '#/components/schemas/PronunciationDictionaryPhonemeRuleRequestModel'
          type: array
          title: Rules
          description: "List of pronunciation rules. Rule can be either:\n    an alias rule: {'string_to_replace': 'a', 'type': 'alias', 'alias': 'b', }\n    or a phoneme rule: {'string_to_replace': 'a', 'type': 'phoneme', 'phoneme': 'b', 'alphabet': 'ipa' }"
          examples:
          - "\n    [\n        {'string_to_replace': 'a', 'type': 'alias', 'alias': 'b' },\n        {'string_to_replace': 'c', 'type': 'phoneme', 'phoneme': 'd', 'alphabet': 'ipa' }\n    ]"
      type: object
      required:
      - rules
      title: Body_Set_rules_on_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__set_rules_post
    GetPronunciationDictionaryMetadataResponseModel:
      properties:
        id:
          type: string
          title: Id
          description: The ID of the pronunciation dictionary.
        latest_version_id:
          type: string
          title: Latest Version Id
          description: The ID of the latest version of the pronunciation dictionary.
        latest_version_rules_num:
          type: integer
          title: Latest Version Rules Num
          description: The number of rules in the latest version of the pronunciation dictionary.
        name:
          type: string
          title: Name
          description: The name of the pronunciation dictionary.
        permission_on_resource:
          anyOf:
          - type: string
            enum:
            - admin
            - editor
            - commenter
            - viewer
          - type: 'null'
          title: Permission On Resource
          description: The permission on the resource of the pronunciation dictionary.
        created_by:
          type: string
          title: Created By
          description: The user ID of the creator of the pronunciation dictionary.
        creation_time_unix:
          type: integer
          title: Creation Time Unix
          description: The creation time of the pronunciation dictionary in Unix timestamp.
        archived_time_unix:
          anyOf:
          - type: integer
          - type: 'null'
          title: Archived Time Unix
          description: The archive time of the pronunciation dictionary in Unix timestamp.
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
          description: The description of the pronunciation dictionary.
      type: object
      required:
      - id
      - latest_version_id
      - latest_version_rules_num
      - name
      - permission_on_resource
      - created_by
      - creation_time_unix
      title: GetPronunciationDictionaryMetadataResponseModel
      example:
        created_by: ar6633Es2kUjFXBdR1iVc9ztsXl1
        creation_time_unix: 1714156800
        description: This is a test dictionary
        id: 5xM3yVvZQKV0EfqQpLrJ
        latest_version_id: 5xM3yVvZQKV0EfqQpLr2
        latest_version_rules_num: 2
        name: My Dictionary
        permission_on_resource: admin
    PronunciationDictionaryAliasRuleRequestModel:
      properties:
        string_to_replace:
          type: string
          title: String To Replace
          description: The string to replace. Must be a non-empty string.
        case_sensitive:
          type: boolean
          title: Case Sensitive
          description: Whether the rule should match case-sensitively.
          default: true
        word_boundaries:
          type: boolean
          title: Word Boundaries
          description: Whether the rule should only match at word boundaries.
          default: true
        type:
          type: string
          const: alias
          title: Type
          description: The type of the rule.
        alias:
          type: string
          title: Alias
          description: The alias for the string to be replaced.
      type: object
      required:
      - string_to_replace
      - type
      - alias
      title: PronunciationDictionaryAliasRuleRequestModel
      example:
        alias: tie-land
        case_sensitive: true
        string_to_replace: Thailand
        type: alias
        word_boundaries: true
    PronunciationDictionaryPhonemeRuleResponseModel:
      properties:
        string_to_replace:
          type: string
          title: String To Replace
        case_sensitive:
          type: boolean
          title: Case Sensitive
          description: Whether the rule matches case-sensitively.
          default: true
        word_boundaries:
          type: boolean
          title: Word Boundaries
          description: Whether the rule only matches at word boundaries.
          default: true
        type:
          type: string
          const: phoneme
          title: Type
        phoneme:
          type: string
          title: Phoneme
        alphabet:
          type: string
          title: Alphabet
      type: object
      required:
      - string_to_replace
      - type
      - phoneme
      - alphabet
      title: PronunciationDictionaryPhonemeRuleResponseModel
    Body_Add_a_pronunciation_dictionary_v1_pronunciation_dictionaries_add_from_rules_post:
      properties:
        rules:
          items:
            anyOf:
            - $ref: '#/components/schemas/PronunciationDictionaryAliasRuleRequestModel'
            - $ref: '#/components/schemas/PronunciationDictionaryPhonemeRuleRequestModel'
          type: array
          title: Rules
          description: "List of pronunciation rules. Rule can be either:\n    an alias rule: {'string_to_replace': 'a', 'type': 'alias', 'alias': 'b', }\n    or a phoneme rule: {'string_to_replace': 'a', 'type': 'phoneme', 'phoneme': 'b', 'alphabet': 'ipa' }"
          examples:
          - "\n    [\n        {'string_to_replace': 'a', 'type': 'alias', 'alias': 'b' },\n        {'string_to_replace': 'c', 'type': 'phoneme', 'phoneme': 'd', 'alphabet': 'ipa' }\n    ]"
        name:
          type: string
          title: Name
          description: The name of the pronunciation dictionary, used for identification only.
          examples:
          - My Dictionary
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
          description: A description of the pronunciation dictionary, used for identification only.
          examples:
          - Contains pronunciation's of our character names
        workspace_access:
          anyOf:
          - type: string
            enum:
            - admin
            - editor
            - commenter
            - viewer
          - type: 'null'
          title: Workspace Access
          description: Should be one of 'admin', 'editor' or 'viewer'. If not provided, defaults to no access.
          examples:
          - viewer
      type: object
      required:
      - rules
      - name
      title: Body_Add_a_pronunciation_dictionary_v1_pronunciation_dictionaries_add_from_rules_post
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    PronunciationDictionaryPhonemeRuleRequestModel:
      properties:
        string_to_replace:
          type: string
          title: String To Replace
          description: The string to replace. Must be a non-empty string.
        case_sensitive:
          type: boolean
          title: Case Sensitive
          description: Whether the rule should match case-sensitively.
          default: true
        word_boundaries:
          type: boolean
          title: Word Boundaries
          description: Whether the rule should only match at word boundaries.
          default: true
        type:
          type: string
          const: phoneme
          title: Type
          description: The type of the rule.
        phoneme:
          type: string
          title: Phoneme
          description: The phoneme rule.
        alphabet:
          type: string
          title: Alphabet
          description: The alphabet to use with the phoneme rule.
      type: object
      required:
      - string_to_replace
      - type
      - phoneme
      - alphabet
      title: PronunciationDictionaryPhonemeRuleRequestModel
      example:
        alphabet: ipa
        case_sensitive: true
        phoneme: /ˈtaɪ.lænd/
        string_to_replace: Thailand
        type: phoneme
        word_boundaries: true
    PronunciationDictionaryAliasRuleResponseModel:
      properties:
        string_to_replace:
          type: string
          title: String To Replace
        case_sensitive:
          type: boolean
          title: Case Sensitive
          description: Whether the rule matches case-sensitively.
          default: true
        word_boundaries:
          type: boolean
          title: Word Boundaries
          description: Whether the rule only matches at word boundaries.
          default: true
        type:
          type: string
          const: alias
          title: Type
        alias:
          type: string
          title: Alias
      type: object
      required:
      - string_to_replace
      - type
      - alias
      title: PronunciationDictionaryAliasRuleResponseModel
    ? Body_Remove_rules_from_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__remove_rules_post
    : properties:
        rule_strings:
          items:
            type: string
          type: array
          title: Rule Strings
          description: List of strings to remove from the pronunciation dictionary.
          examples:
          - '[''a'', ''b'']'
      type: object
      required:
      - rule_strings
      title: Body_Remove_rules_from_the_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__remove_rules_post
    Body_Add_a_pronunciation_dictionary_v1_pronunciation_dictionaries_add_from_file_post:
      properties:
        name:
          type: string
          title: Name
          description: The name of the pronunciation dictionary, used for identification only.
          examples:
          - My Dictionary
        file:
          anyOf:
          - type: string
            format: binary
          - type: 'null'
          title: File
          description: A lexicon .pls file which we will use to initialize the project with.
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
          description: A description of the pronunciation dictionary, used for identification only.
          examples:
          - Contains pronunciation's of our character names
        workspace_access:
          anyOf:
          - type: string
            enum:
            - admin
            - editor
            - commenter
            - viewer
          - type: 'null'
          title: Workspace Access
          description: Should be one of 'admin', 'editor' or 'viewer'. If not provided, defaults to no access.
          examples:
          - viewer
      type: object
      required:
      - name
      title: Body_Add_a_pronunciation_dictionary_v1_pronunciation_dictionaries_add_from_file_post
    Body_Update_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__patch:
      properties:
        archived:
          type: boolean
          title: Archived
          description: Whether to archive the pronunciation dictionary.
          examples:
          - true
        name:
          type: string
          title: Name
          description: The name of the pronunciation dictionary, used for identification only.
          examples:
          - My Dictionary
      type: object
      title: Body_Update_pronunciation_dictionary_v1_pronunciation_dictionaries__pronunciation_dictionary_id__patch
